In [1]:
import pandas as pdty
import numpy as np

In [2]:
import cv2 #computervison

In [3]:
import time #timetofphoto
import datetime #dateoftheday

In [4]:
face_detect = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

In [7]:
source = cv2.VideoCapture(0)
input_images = []
targets = []
count = 0
for i in range(2):
    no_of_images = 0
    input("Enter to start")
    while 1:
        _,image = source.read(0)
        gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
        detected_faces = face_detect.detectMultiScale(gray, 1.2, 9)
        if len(detected_faces) > 1:
            continue
        for each_face in detected_faces:
            x, y, w, h = each_face
            cv2.rectangle(image,(x,y), (x+w, y+h),(0, 0, 255), 3)
            crop = gray[y:y+h, x:x+w]
            cropped_image = cv2.resize(crop,(100, 100))
            input_images.append(cropped_image)
            targets.append(count)

            no_of_images += 1
            cv2.putText(image, "image no : " + str(no_of_images), (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1,(100,100,100), 2)

            cv2.imshow('project', cropped_image)
            key = cv2.waitKey(1)
            cv2.imshow("face window", image)
        if no_of_images == 1500 :
               break

    count += 1

    cv2.destroyAllWindows()
source.release()

In [8]:
input_images

[array([[188, 188, 188, ..., 210, 210, 210],
        [187, 187, 187, ..., 209, 209, 209],
        [186, 186, 186, ..., 208, 208, 207],
        ...,
        [136, 136, 133, ..., 138, 134, 125],
        [136, 136, 134, ..., 130, 123, 110],
        [136, 136, 135, ..., 125, 118, 118]], dtype=uint8),
 array([[182, 181, 184, ..., 206, 207, 208],
        [182, 182, 183, ..., 206, 207, 207],
        [185, 184, 183, ..., 207, 207, 207],
        ...,
        [132, 132, 132, ..., 127, 123, 117],
        [131, 131, 131, ..., 120, 119, 126],
        [129, 131, 130, ..., 117, 124, 147]], dtype=uint8),
 array([[186, 187, 187, ..., 201, 202, 203],
        [187, 187, 187, ..., 200, 200, 201],
        [185, 187, 187, ..., 198, 198, 200],
        ...,
        [135, 134, 134, ..., 142, 141, 140],
        [135, 134, 134, ..., 141, 140, 138],
        [134, 133, 133, ..., 140, 139, 135]], dtype=uint8),
 array([[186, 187, 187, ..., 201, 202, 203],
        [187, 187, 187, ..., 200, 200, 201],
        [185, 18

In [9]:
len(input_images)

3000

In [10]:
len(targets)

3000

In [11]:
input_images_normalized = np.array(input_images)/255.0
input_images_normalized

array([[[0.7372549 , 0.7372549 , 0.7372549 , ..., 0.82352941,
         0.82352941, 0.82352941],
        [0.73333333, 0.73333333, 0.73333333, ..., 0.81960784,
         0.81960784, 0.81960784],
        [0.72941176, 0.72941176, 0.72941176, ..., 0.81568627,
         0.81568627, 0.81176471],
        ...,
        [0.53333333, 0.53333333, 0.52156863, ..., 0.54117647,
         0.5254902 , 0.49019608],
        [0.53333333, 0.53333333, 0.5254902 , ..., 0.50980392,
         0.48235294, 0.43137255],
        [0.53333333, 0.53333333, 0.52941176, ..., 0.49019608,
         0.4627451 , 0.4627451 ]],

       [[0.71372549, 0.70980392, 0.72156863, ..., 0.80784314,
         0.81176471, 0.81568627],
        [0.71372549, 0.71372549, 0.71764706, ..., 0.80784314,
         0.81176471, 0.81176471],
        [0.7254902 , 0.72156863, 0.71764706, ..., 0.81176471,
         0.81176471, 0.81176471],
        ...,
        [0.51764706, 0.51764706, 0.51764706, ..., 0.49803922,
         0.48235294, 0.45882353],
        [0.5

In [13]:
input_images_normalized_reshaped = input_images_normalized.reshape(3000, 100, 100, 1)
input_images_normalized_reshaped

array([[[[0.7372549 ],
         [0.7372549 ],
         [0.7372549 ],
         ...,
         [0.82352941],
         [0.82352941],
         [0.82352941]],

        [[0.73333333],
         [0.73333333],
         [0.73333333],
         ...,
         [0.81960784],
         [0.81960784],
         [0.81960784]],

        [[0.72941176],
         [0.72941176],
         [0.72941176],
         ...,
         [0.81568627],
         [0.81568627],
         [0.81176471]],

        ...,

        [[0.53333333],
         [0.53333333],
         [0.52156863],
         ...,
         [0.54117647],
         [0.5254902 ],
         [0.49019608]],

        [[0.53333333],
         [0.53333333],
         [0.5254902 ],
         ...,
         [0.50980392],
         [0.48235294],
         [0.43137255]],

        [[0.53333333],
         [0.53333333],
         [0.52941176],
         ...,
         [0.49019608],
         [0.4627451 ],
         [0.4627451 ]]],


       [[[0.71372549],
         [0.70980392],
         [0.72

In [14]:
from keras.utils import to_categorical
targets = to_categorical(targets)
targets

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [15]:
targets[ : 100]

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_train, x_test, y_train, y_test = train_test_split(input_images_normalized_reshaped, targets)

In [18]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((2250, 100, 100, 1), (750, 100, 100, 1), (2250, 2), (750, 2))

In [19]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Conv2D, MaxPooling2D, Dropout, Flatten
from tensorflow.keras.optimizers import SGD
from keras.callbacks import ModelCheckpoint

In [20]:
model = Sequential()
model.add(Conv2D(300, (3,3),input_shape=(100, 100, 1)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(100, (3,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Dropout(0.3))
model.add(Flatten())

model.add(Dense(50, activation='relu'))
model.add(Dense(2, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

c:\Users\Varshitha Reddy\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [21]:
cp = ModelCheckpoint('best_one.keras', verbose=0, save_best_only=True)
model.fit(x_train, y_train, epochs = 3, callbacks=[cp], validation_split=0.2)

Epoch 1/3
57/57 ━━━━━━━━━━━━━━━━━━━━ 117s 2s/step - accuracy: 0.7286 - loss: 0.6956 - val_accuracy: 0.8600 - val_loss: 0.2886
Epoch 2/3
57/57 ━━━━━━━━━━━━━━━━━━━━ 114s 2s/step - accuracy: 0.8872 - loss: 0.2754 - val_accuracy: 0.8667 - val_loss: 0.4124
Epoch 3/3
57/57 ━━━━━━━━━━━━━━━━━━━━ 124s 2s/step - accuracy: 0.8974 - loss: 0.2267 - val_accuracy: 0.9133 - val_loss: 0.2121


In [22]:
from tensorflow.keras.models import load_model
model = load_model('best_one.keras')

In [23]:
import os
import smtplib
from twilio.rest import Client
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email.mime.image import MIMEImage
from email import encoders

In [ ]:
source = cv2.VideoCapture(0)

while 1:
    _, image = source.read(0)
    gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
    detected_faces = face_detect.detectMultiScale(gray, 1.2, 9)
    if len(detected_faces) > 1:
        continue
    for each_face in detected_faces:
        x, y, w, h = each_face
        cv2.rectangle(image, (x, y), (x+w, y+h), (0, 0, 255), 3)
        crop = gray[y:y+h, x:x+w]
        cropped_image = cv2.resize(crop, (100, 100))
        normalized_image = cropped_image/255
        reshaped_face = np.reshape(normalized_image, (1, 100, 100, 1))
        result = model.predict(reshaped_face)[0]
        if result[0] >  result[1]:
            cv2.rectangle(image, (x, y), (x + w, y + h), (0, 255, 0), 2)
            cv2.putText(image, "family member", (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
            
            # Your Account SID and Auth Token from twilio.com/console
            account_sid = 'xxxxxxxxxxxxxxxxxxxxx'
            auth_token =  'xxxxxxxxxxxxxxxxxxxxx'
            
            to_phone_number = '+91xxxxxxxxxx'  # The recipient's phone number
            from_phone_number = '+xxxxxxxxxxx'  # Your Twilio phone number
            message_body = 'Family member entered your room!'
            client = Client(account_sid, auth_token)
            message = client.messages.create(body=message_body,from_=from_phone_number,to=to_phone_number)

            sub_face = image[y:y+h, x:x+w]

            #this is the location where image is saved in .jpg extension
            FaceFileName = "Location" + str(y) + ".jpg"

            time.sleep(5)
            cv2.imwrite(FaceFileName, sub_face)

            msg = MIMEMultipart()
            img_data = open(FaceFileName, 'rb').read()
            msg['Subject'] = 'There is a Family member'
            msg['From'] = 'from@gmail.com'  # email_id fron which the mail is to be sent
            msg['To'] = 'to@gmail.com'      # email_id to which the mail is to be sent
            password='app_password'         # the app_password of from@gmail.com

            message = "Family member Entered Your Room"
            msg.attach(MIMEText(message, 'plain'))
            img = MIMEImage(img_data, name=os.path.basename(FaceFileName))
            msg.attach(img)
            s = smtplib.SMTP_SSL('smtp.googlemail.com' , 465)
            s.ehlo()


            s.login(msg['From'], password)
            s.sendmail(msg['From'], msg['To'], msg.as_string())
            break


        if result[1] >  result[0]:
            cv2.rectangle(image, (x, y), (x + w, y + h), (0, 0, 255), 2)
            cv2.putText(image, "intruder", (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)

            # Your Account SID and Auth Token from twilio.com/console
            account_sid = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
            auth_token = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
            to_phone_number = '+91xxxxxxxxxx'  # The recipient's phone number
            from_phone_number = '+xxxxxxxxxxx'  # Your Twilio phone number
            message_body = 'Intruder entered your room!'
            client = Client(account_sid, auth_token)
            message = client.messages.create(body=message_body,from_=from_phone_number,to=to_phone_number)


            sub_face = image[y:y+h, x:x+w]

            #this is the location where image is saved in .jpg extension
            FaceFileName = "Location" + str(y) + ".jpg"

            time.sleep(5)
            cv2.imwrite(FaceFileName, sub_face)

            msg = MIMEMultipart()
            img_data = open(FaceFileName, 'rb').read()
            msg['Subject'] = 'There is a Family member'
            msg['From'] = 'from@gmail.com'  # email_id fron which the mail is to be sent
            msg['To'] = 'to@gmail.com'      # email_id to which the mail is to be sent
            password='app_password'         # the app_password of from@gmail.com

            message = "Someone Entered Your Room"
            msg.attach(MIMEText(message, 'plain'))
            img = MIMEImage(img_data, name=os.path.basename(FaceFileName))
            msg.attach(img)
            s = smtplib.SMTP_SSL('smtp.googlemail.com' , 465)
            s.ehlo()


            s.login(msg['From'], password)
            s.sendmail(msg['From'], msg['To'], msg.as_string())
            break







    cv2.imshow('Project', image)
    key = cv2.waitKey(1)
    if key == 23:
        break
cv2.destroyAllWindows()
source.release()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


In [24]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
# Predict on the test set
y_pred = model.predict(x_test)

# Convert the predictions from one-hot encoding to class labels
y_pred_labels = np.argmax(y_pred, axis=1)
y_test_labels = np.argmax(y_test, axis=1)

# Calculate accuracy
accuracy = accuracy_score(y_test_labels, y_pred_labels)
print(f"Accuracy: {accuracy:.4f}")

# Calculate precision
precision = precision_score(y_test_labels, y_pred_labels)
print(f"Precision: {precision:.4f}")

# Calculate recall
recall = recall_score(y_test_labels, y_pred_labels)
print(f"Recall: {recall:.4f}")

# Confusion matrix
conf_matrix = confusion_matrix(y_test_labels, y_pred_labels)
print("Confusion Matrix:")
print(conf_matrix)

24/24 ━━━━━━━━━━━━━━━━━━━━ 11s 436ms/step
Accuracy: 0.9160
Precision: 0.9812
Recall: 0.8464
Confusion Matrix:
[[373   6]
 [ 57 314]]
